- name: Search for incident using host instead of instance
  hosts: localhost
  tasks:
  - name: sleep for 300 seconds
    shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    
  # - name: Get environment
  #   debug:
  #     msg: "{{ ansible_env }}"
      
  - snow_record_find:
      username: "{{ Username }}"
      password: "{{ Password }}"
      host: dev49922.service-now.com
      table: incident
      query:
        assignment_group: 8a5055c9c61122780043563ef53438e3
      return_fields:
        - number
        - opened_at
        - sys_id
    register: snow_incidents

  - name: Display incident information
    debug:
      msg: "{{ item.number }} - {{ item.short_description }}"
    loop: "{{ snow_incidents.records }}"
    
  - debug: 
      msg: "{{ snow_incidents }}"
