- name: Search for incident using host instead of instance
  hosts: localhost
  tasks:
  - name: Update /etc/resolv.conf file
    shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf

  - snow_record_find:
      username: "{{ Username }}"
      password: "{{ Password }}"
      host: dev49922.service-now.com
      table: incident
      query:
        AND:
          equals:
            active: "True"
            #type: "standard"
            assignment_group: 8a5055c9c61122780043563ef53438e3
      # return_fields:
      #   - number
      #   - opened_at
      #   - sys_id
    register: snow_incidents
    
  # - debug: 
  #     msg: "{{ snow_incidents }}"

  - name: Display incident information
    debug:
      msg: "{{ item.number }} - {{ item.short_description }}"
    loop: "{{ snow_incidents.record }}"
    

