---
- name: Resolve Incident in ServiceNow
  hosts: localhost
  tasks:
    - name: Use snow_record to resolve an incident
      snow_record:
        instance: dev141954
        username: admin
        password: N$g6QjIQ2u%o
        table: incident
        state: present
        sys_id: a9e30c7dc61122760116894de7bcc7bd
        data:
          state: 6  # Resolved state (adjust the state value according to your ServiceNow instance)
          assigned_to: 681b365ec0a80164000fb0b05854a0cd
          short_description: "Solved"  # Adjust the close code as needed
          work_notes: "Incident has been resolved."  # Your resolution notes
      delegate_to: localhost
