- name: Search for incident using host instead of instance
  hosts: localhost
  tasks:
  #- command: echo "hello Ansible"
  - snow_record_find:
      username: admin
      password: 5Z8StfpN$eW*
      host: dev49922.service-now.com
      table: incident
      query:
        assignment_group: 8a5055c9c61122780043563ef53438e3
      return_fields:
        - number
        - opened_at
