# - name: Windows server ping test
#   hosts: localhost
#   gather_facts: false
#   tasks:
#   - name: Update /etc/resolv.conf file
#     shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf;/usr/bin/pip3 install pywinrm


- name: Windows server ping test
  hosts: 192.168.56.142
  gather_facts: false
  tasks:
  - name: ping test
    ping:
    delegate_to: localhost 
  - name: print hostname
    shell: hostname
    register: output
  - debug:
      msg: "{{ output }}"
