- name: Get NetBackup Snow incidents
  hosts: all
  #connection: local
  gather_facts: false
  vars_files:
    - ../variable/default.yml
  tasks:
  - name: Update /etc/resolv.conf file
    shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf;/usr/bin/pip3 install pywinrm
  - name: ping test
    ping:
    delegate_to: localhost 
