- name: Windows server ping test
  hosts: all
  gather_facts: false
  tasks:
  - name: Update /etc/resolv.conf file
    shell: echo "nameserver 8.8.8.8" >> /etc/resolv.conf;/usr/bin/pip3 install pywinrm
  - name: ping test
    ping:
    delegate_to: localhost 
